language: java
sudo: false
jdk: oraclejdk8

env:
  matrix:
    - JDK_FOR_TEST=oraclejdk8
#    - JDK_FOR_TEST=oraclejdk9

# Java 9 is not currently officially supported, so install it manually
matrix:
  include:
     env: JDK_FOR_TEST=oraclejdk9
     addons:
       apt:
         packages:
           - oracle-java9-installer

install:
  - if [ -e eclipse.tar.gz ]; then wget http://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops/R-3.6.2-201102101200/eclipse-SDK-3.6.2-linux-gtk-x86_64.tar.gz -O eclipse.tar.gz; fi
  - rm -rf $(pwd)/eclipse
  - tar xzvf eclipse.tar.gz eclipse
  - echo eclipsePlugin.dir=$(pwd)/eclipse/plugins > eclipsePlugin/local.properties

script:
  # Manually switch to JDK9 if needed
  - if [[ $JDK_FOR_TEST == "oraclejdk9" ]]; then remove_dir_from_path $JAVA_HOME/bin; export JAVA_HOME=/usr/lib/jvm/java-9-oracle; export JAVA_HOME=/usr/lib/jvm/java-9-oracle; fi
  - ./gradlew build smoketest -S

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - eclipse.tar.gz
