language: java
dist: trusty
git:
  depth: false
jdk:
  - openjdk8
  - openjdk11
matrix:
  allow_failures:
  - jdk: openjdk11
env:
  global:
    - SONAR_HOST_URL="https://sonarcloud.io"

    # SONAR_LOGIN value
    # please note this value is available for pull requests from the same repository only
    # see https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
    - secure: "FjzPYgjdN9WRvAwvJDFP0MqWMOsqCG0tNO6ts7X1p6HWikpoHnTqWgMl0YOgGK93trvB6vtIisZVVdLZG1rCwnXlO4Xd+6f+nhsJDledd9b4EePQPECJbHZZ8Hg69ATIlm7chll73GZzWTAL2Q3pIdsEJbwtqPzJ/j0H4COkayDeQ4ERA50pvvkXTiQrwxc5URrNH36ZOn10hfUEKO03EKbAlD+5dOzcxqu5WiS7j10zbMBCrKqhzN+zJQSOuDCTQz2S8McJBTiz4kMEBkF1q4Ax+1ywz2vICL3/F5/xqnHvHOk9wZE/4OOiNxjqxVd+Ik6LGE1BbLuATQz0Cmc3DiqsGYBsKtlk88v1QX2hsND/K0hwda/uItzbh95HmnrRYHYhzOcgcIVRqVwoPkYYWPYr9S2f3DGlFEnlGwJHgvqjuwMJaBmm2zblxPammEx3XoWqrKQ7RrelH1tUTWXy/tRss4Fof+D33/NJqa71Xvph1meKMcu+OOVatCul1IJaTtf2pyyifLTNRntgl4C4ok57PN882lRp55/Ifmi+xbt3Nd7lM1Fpy2eDugK1UINmkjRQsyCZY3EVgcM/NkrMa6qHhZFu5F1iv3EBYRiV/WKJ9PtTErkTeX1JZtyZYo7yS+VlIXIJFLoxfrV9TH5B3kczVILxgfJJ6gVPQOY5984="

    - secure: "bNbHxR43FHIWX/im5GUZD52UF0FszM5kxhw/3DFqpaOWEpf3BtvSTDpHvOdbVmcD+HtC8cCaXViCQaSIsDWuP2LrxxGlULl/a9yF5FLq+BxyTx28+Xi6c+mXSeava82poWEbF6whiLrn8GIIC+z2xwpphT+bBXj/3UmOmPj/cxfsuzb6gH95Xk1OhQJjhJ0Lt6muO0YmxA4dAtNDJHHwTU/GVn25+41WiAO1P4tDHRnPdAZFXnbM5kPV41KmYw4/0YbPgr5aJuAyrUD86ufwJR0Zp+TR4JJB+miw9+XYUgjRMgPBSS3VChOnYugKClfwVq8MwxRpUpBjG5eszt64TxgeEX0sTLBv9JwxUu5R+uCYgQvSdVKduyQYVTdJnMqTsVFCeOQlF0XHXvRXK7+SSNjkpaV/TMlfZ0vY+BAUnBIUAsMjvpX9RNMvDYx5D/5/cqj9WiEsaBLBLuQX90bZA0B8xbA1IHj9pRSxm9N8VAWMTzxhZzuqqMAi2IszBRZicKKYd66z83T1k9SFcTY4mvg0W2uVvZsoaBMIYmhvBZXPOLEgwadTbeiqFW2vox16k6k8xRlKzH+IIYQAChFPqxDxBtP8b7LZDa6ahreBMKtp3xBPbbCgbrviE647CwyPwb+DxOihua5GNfgxXby4kxiXcuglUXZ5NWCmvks2KIE="

    - SIGNING_KEY_ID="EECF0E90"
    # SIGNING_PASSWORD value
    - secure: "XGuUFU4g2jgx80Dnef1M4xWMKtooPfIGKlQv93InPN/NLR0TEwWztHgSd+PqsfgFbJzfx9ZkcuZ/YFOofsVrdQcAf3iGpA+nEWzcOu+TucY1ELExZe1UaT5IckFU3qnIOU/GKQEW41PQrZZ/yDhGzlZnaE4KBty0Qs9EtHn7lS+pMt44986e24w+2KfSRwW24KMS7J1pvX4li7423OLUuZusICIPWB74AcoE0hrtsF2GK7MjXDvRhKovIOyqYsZ4bHHdwrx8Fp14lsqeMMTGNMMuZhtq4e2TOue47MBRd4s3U/N8a5wJzmlFagW+Zrr/2fbvfXEmn0PLoTMYbSLNq4XJqawYPBCk1Cf8OeYeQki/msUQxx8RYQxuS1mmtUnl6+4JzJ42/lMRuLWm5Pb4St1lZV4G58luh2/7DItUKpLm9qGZ3AvmNGyRC1aEIoinC43ZTpDJalmKHLk3JXbvCH/fLrTLz4cxX+5Wfo1NvOVZGXcMM5Wmcp9+mOSFBRkIq4Bjo+WvIE/QKdn8JoJHUZIKwviRZbocjAuBp0JCoaWSWYuBBlauQLrUpc2oLAjql2Pxyn5E2AfnvE6lZh5RSQ8cqvheM9LaXBGd2PualqWsHkJSugqGd7AiKmiAotGtWZPWtlje3NW7bL6AMT6d8GTYmSRKKuUFISKU3sqzV2s="

    # GITHUB_TOKEN value to push changes to GitHub; Currently it is ued to update gh-pages branch of spotbugs/eclipse-latest etc.
    - secure: "dFmNTEiYr0XHd2Zoj95j1xqoawNIrN63pgvHwKWf5ngNkncxLukKu1nGvvt9Fbw4/Embgzvz2GRwxWJBu5//yKrUHD9ILBS78Sn8nxpba7wHE6r8k6m+u7dOeN4jEH1fzyzsniSq939S6uB8gvfhhikddh9oZzwZnMq1YVyHQaWzbcaUnom+cwndKfK+YXg5mkt5Z92uXkJjGqd36FPA3GrlGJH7kXgWhVXI7Vds2hHsX/IBG0/2ZDhKNSZ8AiaDU4g2pSBlqA7F/noFW68hpohz9AAjku2COmpK0Ojd/iE0bVclXHYzs2aZq3lvYb3gv0dTEJrcIwPlDKQZWaEV/SxX9nIOqL5Q6XeVigTmnKkivQQ/b0hMPEpeHVvipMETYVzDvFT0qatLX/gUsiLgRPilWu0imFvNY4YAPZK3UPBSL5g+/8DzDPmTMZiOqJTMuMr+r/c7ch8qfjoaibc6LqUSJYLxyfk3NeturoviPLiBBtoadNsLPddtsNE8MZhr9lwRefNXY/VPBUxi7Bpxo7KfZ0BDSTzKeW7AEm/9E4CDmbd25eYGdvfVFeElGt5iTAfwIBYhj/GDkqnjesNCyDeNry/NywnEigkZQ4gzIvkHDkevUFs19nSspBmxiK82doY/j9Q0/TAK30mIdhg8VQwmkq5AYVIcN8kCu8WBhxw="
    # GRADLE_PUBLISH_KEY value
    - secure: "lZc3FKJlHOKrtYJp2Tc+SDLTye5vip0Hp2jpLj9GwxyP74DgmfzdABeptcvbfbxAHP7+emAyV7en0jdfS6iK9YWDTKpu4FKH/WrH4b03ArdkowJTYQI1pi2TLBlUNg64xaP/eeao1oWg44jCqp/sbU414zlA3+9gynnGED3mpsRQieRF3niBIt2bnzIeIusWxIqMWCXSzRnxC4RvlYpV7lhhJQb+2nJRets/KykhGs4RZj+bZB2I/WqgorzVN8GXBKevjAvR6HCaVClfa9A5boA4qsxb1P7UEurcMT4dJUXJHCW1tMBXpGDxtyNAhJgbKr4cVL7skzVsDaqSE1szLNwnDf9P5+a23EZeaT7juVsf7kXpR4KZ1JRWbss6Md035Px0KrbNFGtiojdtqRHBkAYnNNB1AwfeD4ZmsRip7oKU7mnwXOK5yUtuFnssZaIVIQHeGeNJOmtL69ELhEju07fmellIf5+fpBYwJVj62t/MvTEt9I1NbXCNPHpeHOVq6HY8OhMQ0Gzpzy8OfM/F6Nu8lowFV9LK/G3NZ7Uh206xZ+ArGDJ59a3mjsJ0eIVbkar1XxoJDZkQrrUx3GSN19o4Jw8y62V9E5A486nA3zjRSl5uOUhbnPTNO9RsxcIvwFx1dHYTTXkZMLqZarvhSjj+Pi0mCLxKjcoUyvtWZMk="
    # GRADLE_PUBLISH_SECRET value
    - secure: "mfFuR4+xh23Q71jdwv43hL4LnwNPE3m3zH4h+q5XkNeKbdEQMb+Sn5nXmhgR/vJ9zFTchmlmyg4bjEdV4Dc65g2kNPSu0CvSgn+ypURhPwvN+5JAeplh+XBqtE8gVh8qxCXAR4ZCVsEEUg4KyW+Rb9U0Uuy04b+45f1RfjqO5dayYvob0DQg3c5OrqyQ6pD88Y2LGUjfVAB+/8RZvvLJeEQTvBvISNceBCTxQrRt00y8f9p2VqqLG5lVZD1mnceIRgLWIkTiK/nxUqOh5IBpeyUF6Y9/uLKNeNn/5U11RnYL4O3XMICReBD/HcwW4hVTT+gAg8vNVVTuANbyG8AcsWGTF0Yck52W8DK9j07vGIeqgqDetvmh+a+hvCwsfpM9Wl0sv5lx7iim9VSE2DappFDaWKRF8ixGvjndL8Up8yCsfdJPYVafH81Ybv+Fd5GQX59Q5GIQs2IYFZ7312wzRswFfy5j1Hn74cnQWInxtbn7SXVaRj5CswEFearua38KDjkrx0GY1pt3ypbjf//kkgPmjRj8PRtPe/SEuZvCWlqBOym8QkZ2mIhiPn+pz6RO+mNRll5bmAaOtHLLkcIziMuFD7fi1YrCtCuY3PKiW0Xt7NHQQlD+y6X3RK2qsV8txPGXZz3F2Cnk9GvJepQv14hbc8OKPtJdJG/2uaLUuDg="

addons:
  apt:
    packages:
      - openjdk-8-jdk-headless

before_install:
  - mkdir -p deps
  # In forked repository, encrypted environment variable is undefined. We need to skip this decryption.
  - if [ -n "$encrypted_05a1b17af1e9_key" ]; then openssl aes-256-cbc -K $encrypted_05a1b17af1e9_key -iv $encrypted_05a1b17af1e9_iv -in .travis/secring.gpg.enc -out secring.gpg -d; fi
  - if [ -n "$encrypted_00ea871ed050_key" ]; then openssl aes-256-cbc -K $encrypted_00ea871ed050_key -iv $encrypted_00ea871ed050_iv -in .travis/spotbugs.jks.enc -out spotbugs.jks -d; fi

install:
  - if [[ ! -e deps/eclipse-SDK-4.6.3-linux-gtk-x86_64.tar.gz ]]; then wget 'https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.6.3-201703010400/eclipse-SDK-4.6.3-linux-gtk-x86_64.tar.gz&r=1' -O deps/eclipse-SDK-4.6.3-linux-gtk-x86_64.tar.gz; fi
  - rm -rf eclipse
  - tar xzvf deps/eclipse-SDK-4.6.3-linux-gtk-x86_64.tar.gz eclipse
  - echo eclipseRoot.dir=$(pwd)/eclipse > eclipsePlugin/local.properties
  - echo ossrhUsername=eller86 >> gradle.properties
  - echo "ossrhPassword=${SONATYPE_PASSWORD}" >> gradle.properties
  - echo "signing.keyId=${SIGNING_KEY_ID}" >> gradle.properties
  - echo "signing.password=${SIGNING_PASSWORD}" >> gradle.properties
  - echo signing.secretKeyRingFile=${TRAVIS_BUILD_DIR}/secring.gpg >> gradle.properties
  - echo "keystorepass=${KEYSTORE_PASS}" >> gradle.properties

script:
  - jdk_switcher use openjdk8
  - ./gradlew classes testClasses -S
  - if [[ $TRAVIS_JDK_VERSION == "openjdk11" ]]; then export JAVA_HOME=$HOME/openjdk11; fi
  - ./gradlew -v --no-daemon
  - ./gradlew build smoketest -S --no-daemon
  - jdk_switcher use openjdk8
  - if [[ $TRAVIS_JDK_VERSION == "openjdk8" ]]; then ./gradlew sonarqube -S; fi
  - if [[ $TRAVIS_JDK_VERSION == "openjdk8" ]]; then ./gradlew spotlessCheck -S; fi

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - deps/

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: eclipsePlugin/build/site/eclipse-daily
    repo: spotbugs/eclipse-latest
    email: skypencil+spotbugs-bot@gmail.com
    on:
      branch: master
      jdk: openjdk8
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: eclipsePlugin/build/site/eclipse-candidate
    repo: spotbugs/eclipse-candidate
    email: skypencil+spotbugs-bot@gmail.com
    on:
      tags: true
      jdk: openjdk8
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: eclipsePlugin/build/site/eclipse
    repo: spotbugs/eclipse
    email: skypencil+spotbugs-bot@gmail.com
    on:
      tags: true
      jdk: openjdk8
      condition: "$TRAVIS_TAG != *'_RC'* && $TRAVIS_TAG != *'_beta'*"
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "eclipsePlugin/build/distributions/eclipsePlugin.zip"
    skip_cleanup: true
    on:
      tags: true
      jdk: openjdk8
  - provider: script
    skip_cleanup: true
    # wait until uploading task finishes, because it may cost more than 10 minutes without any output
    # https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
    script: .travis/travis_wait "./gradlew publish"
    on:
      jdk: openjdk8
      branch: master
  - provider: script
    skip_cleanup: true
    # wait until uploading task finishes, because it may cost more than 10 minutes without any output
    # https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
    script: .travis/travis_wait "./gradlew publish"
    on:
      tags: true
      jdk: openjdk8
